feat(binaries): Change to use current file name instead someone hardcoded

diff --git a/binaries/.local/bin/n-epub-to-pdf b/binaries/.local/bin/n-epub-to-pdf
--- a/binaries/.local/bin/n-epub-to-pdf
+++ b/binaries/.local/bin/n-epub-to-pdf
@@ -1,15 +1,22 @@
 #!/usr/bin/env bash
 
 function main {
-    pandoc uwu.epub \
-        -o uwu.pdf \
+    # Get the filename from the command line argument
+    filename="${1##*/}"
+
+    if [ -z "$filename" ]; then
+        echo "Error: No filename provided."
+        exit 1
+    fi
+
+    # Convert file using pandoc
+    pandoc "${filename}" \
+        -o "${filename%.epub}.pdf" \
         --pdf-engine=lualatex \
         --standalone \
         -V mainfont:"Merriweather" \
         -V monofont="Maple Mono NF" \
         -V linestretch=1.25
-
-        # -V fontsize=24px \
 }
 
-main
+main "$@"
